import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { RiGithubFill, RiReactjsLine } from "react-icons/ri";
import { IoMdMail } from "react-icons/io";
import {
  SiSpring,
  SiPython,
  SiAngular,
  SiMicrosoftazure,
} from "react-icons/si";
import { BsFiletypeJava } from "react-icons/bs";
import { AiFillLinkedin } from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const urlGithub = "https://github.com/Ming424";
  const urlLinkedin = "https://www.linkedin.com/in/tianming-chen/";
  const urlMailTo = "mailto:tianming.chen0424@gmail.com";
  const urlResume =
    "https://drive.google.com/file/d/1ws_zF5NWkiuNjjOoplQPygGm3AyGORsH/view?usp=sharing";

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section
        className="bg-gray-100 flex items-center justify-between p-3 md:px-8 text-gray-900"
        aria-label="Global"
      >
        <div className="hidden lg:flex gap-x-12">
          <a href="#" className="text-sm font-semibold leading-6">
            Entertainement
          </a>
          <a href="#" className="text-sm font-semibold leading-6">
            Housing
          </a>
          <a href="#" className="text-sm font-semibold leading-6">
            Media
          </a>
        </div>
      </section>

      <main className="bg-white dark:bg-gray-900 dark:text-white">
        {/* CONTENT WRAPPER */}
        <div className="px-5  md:px-20 lg:px-40 max-w-screen-2xl mx-auto">
          <section>
            {/* NAVBAR */}
            <nav className="py-5 mb-0 sm:py-10 md:mb-12 flex justify-between">
              {/* font-burtons was defined in tailwind config */}
              <h1 className=" text-xl font-burtons">Thierry</h1>
              <ul className="flex items-center">
                <li>
                  {/* button dark mode toogle */}
                  <BsFillMoonStarsFill
                    onClick={() => setDarkMode(!darkMode)}
                    className="cursor-pointer text-2xl"
                  />
                </li>
                <li>
                  <a
                    className="cursor-pointer bg-gradient-to-r from-cyan-500 to-blue-400 text-white
                    px-4 py-2 rounded-md ml-8 
                         hover:ring-2 dark:ring-offset-gray-900 hover:ring-offset-2 hover:ring-blue-400 transition-all  duration-200"
                    onClick={() => window.open(urlResume, "_blank")}
                  >
                    <span className="">Resume</span>
                  </a>
                </li>
              </ul>
            </nav>

            {/* CONTENT */}
            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap text-center p-10">
              {/* LEFT - DESCRIPTION */}
              <div className="basis-1/3 flex-1">
                <h2 className="tx-name text-5xl py-2 text-transparent bg-clip-text bg-gradient-to-r from-teal-400 to-blue-600 font-extrabold md:text-6xl py-6">
                  <span className="">Thierry Chen</span>
                </h2>
                <h3 className="text-2xl py-2 md:text-3xl">
                  Software Developer
                </h3>
                {/* max-w-wl for max width paragraph */}
                <p className="text-md py-5 leading-8 text-gray-800 dark:text-white md:text-xl max-w-xl mx-auto">
                  Hello, I'm Thierry, a software engineer specializing in
                  fullstack development. Focus on Spring, Angular and React.
                  Sensible to architecture and ux design. With a keen eye for
                  detail and a deep understanding of programming concepts, I
                  strive to deliver high-quality software solutions that exceed
                  expectations.
                </p>
                <div className="text-4xl flex justify-center gap-16 py-3 text-gray-600">
                  <div className="group relative">
                    <RiGithubFill
                      className="cursor-pointer hover:scale-110 transition duration-100"
                      onClick={() => window.open(urlGithub, "_blank")}
                    />
                    <span className="text-white text-sm pointer-events-none absolute top-13 -left-3 w-max opacity-0 transition-opacity group-hover:opacity-50 bg-black rounded px-2">
                      GitHub
                    </span>
                  </div>
                  <div className="group relative">
                    <AiFillLinkedin
                      className="cursor-pointer hover:scale-110 transition duration-100"
                      onClick={() => window.open(urlLinkedin, "_blank")}
                    />
                    <span className="text-white text-sm pointer-events-none absolute top-13 -left-4 w-max opacity-0 transition-opacity group-hover:opacity-50 bg-black rounded px-2">
                      LinkedIn
                    </span>
                  </div>
                  <div className="group relative">
                    <IoMdMail
                      className="cursor-pointer hover:scale-110 transition duration-100"
                      onClick={() => window.open(urlMailTo)}
                    />
                    <span className="text-white text-sm pointer-events-none absolute top-13 -left-1.5 w-max opacity-0 transition-opacity group-hover:opacity-50 bg-black rounded px-2">
                      Email
                    </span>
                  </div>
                </div>
              </div>
              {/* RIGHT - PICTURE */}
              <div className="basis-1/4 flex-1">
                <div className="relative mx-auto bg-gradient-to-b from-blue-400 to-teal-200 rounded-full w-80 h-80 overflow-hidden md:h-96  md:w-96  hover:ring-4 dark:ring-offset-gray-900 hover:ring-blue-300  hover:ring-offset-4 transition-all duration-200">
                  <Image src={deved} layout="fill" objectFit="cover"></Image>
                </div>
              </div>
            </div>
          </section>

          {/* EXPERTISE */}
          <section className="mt-10 md:mt-20 ">
            <div className="grid py-2 grid-cols-1 md:grid-cols-2 gap-4 ">
              <div className="item-card item-green">
                <div className="flex items-center">
                  <SiSpring />
                  &nbsp;Spring
                </div>
                <div className="font-light">bean, injection</div>
              </div>
              <div className="item-card item-language">
                <div className="flex items-center">
                  <BsFiletypeJava className="text-red" />
                  &nbsp;Java
                </div>
                <div className="font-light">
                  stream, thread, thread pool, synchornization
                </div>
              </div>
              <div className="item-card item-language">
                <div className="flex items-center">
                  <SiPython />
                  &nbsp;Python
                </div>
                <div className="font-light">leetcode</div>
              </div>
              <div className="item-card item-web">
                <div className="flex items-center">
                  <SiAngular />
                  &nbsp;Angular
                </div>
                <div className="font-light">
                  binding, lifecycle, injection, ts, responsive
                </div>
              </div>
              <div className="item-card item-web">
                <div className="flex items-center">
                  <RiReactjsLine className="text-xl" />
                  &nbsp;React
                </div>
                <div className="font-light">
                  react hook, life cycle, responsive
                </div>
              </div>
              <div className="item-card item-support">
                <div className="flex items-center">
                  <SiMicrosoftazure />
                  &nbsp;Azure
                </div>
                <div className="font-light">practicing</div>
              </div>
            </div>
            <div className="grid py-2 grid-cols-4 md:grid-cols-6 gap-3">
              <div className="item-card item-language">SQL</div>
              <div className="item-card item-language">GO</div>
              <div className="item-card item-web">Mongo</div>
              <div className="item-card item-web">Vue</div>
              <div className="item-card item-system">Docker</div>
              <div className="item-card item-system">Ubuntu</div>
            </div>
            <div className="grid py-2 grid-cols-4 md:grid-cols-7 gap-3">
              <div className="item-card item-support">Mockito</div>
              <div className="item-card item-support">Sonar</div>
              <div className="item-card item-support">Postman</div>
              <div className="item-card item-design">Figma</div>
              <div className="item-card item-design">Photoshop</div>
              <div className="item-card item-design">Premier</div>
              <div className="item-card item-system">Unity</div>
            </div>
          </section>

          <section></section>

          <section>
            <div>
              <h3 className="text-3xl py-1 dark:text-white ">
                Services I offer
              </h3>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                Since the beginning of my journey as a freelance designer and
                developer, I've done remote work for
                <span className="text-teal-500"> agencies </span>
                consulted for <span className="text-teal-500">startups </span>
                and collaborated with talanted people to create digital products
                for both business and consumer use.
              </p>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                I offer from a wide range of services, including brand design,
                programming and teaching.
              </p>
            </div>
            {/* CARD */}
            <div className="lg:flex gap-10 dark:text-black">
              <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white  flex-1">
                <Image
                  className="mx-auto"
                  src={design}
                  width={100}
                  height={100}
                />
                <h3 className="text-lg font-medium pt-8 pb-2  ">
                  Beautiful Designs
                </h3>
                <p className="py-2">
                  Creating elegant designs suited for your needs following core
                  design theory.
                </p>
                <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
                <p className="text-gray-800 py-1">Photoshop</p>
                <p className="text-gray-800 py-1">Illustrator</p>
                <p className="text-gray-800 py-1">Figma</p>
                <p className="text-gray-800 py-1">Indesign</p>
              </div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
                <Image
                  className="mx-auto"
                  src={code}
                  width={100}
                  height={100}
                />
                <h3 className="text-lg font-medium pt-8 pb-2 ">
                  Code your dream project
                </h3>
                <p className="py-2">
                  Do you have an idea for your next great website? Let's make it
                  a reality.
                </p>
                <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
                <p className="text-gray-800 py-1">Photoshop</p>
                <p className="text-gray-800 py-1">Illustrator</p>
                <p className="text-gray-800 py-1">Figma</p>
                <p className="text-gray-800 py-1">Indesign</p>
              </div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
                <Image
                  className="mx-auto"
                  src={consulting}
                  width={100}
                  height={100}
                />
                <h3 className="text-lg font-medium pt-8 pb-2 ">Consulting</h3>
                <p className="py-2">
                  Are you interested in feedback for your current project? I can
                  give you tips and tricks to level it up.
                </p>
                <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
                <p className="text-gray-800 py-1">Photoshop</p>
                <p className="text-gray-800 py-1">Illustrator</p>
                <p className="text-gray-800 py-1">Figma</p>
                <p className="text-gray-800 py-1">Indesign</p>
              </div>
            </div>
          </section>
          <section>
            <div>
              <h3 className="text-3xl py1"></h3>Portofolio
            </div>
            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
              <div className="basis-1/3 flex-1">
                <Image
                  src={web1}
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                />
              </div>
              <div className="basis-1/3 flex-1">
                <Image
                  src={web2}
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                />
              </div>
              <div className="basis-1/3 flex-1">
                <Image
                  src={web3}
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                />
              </div>
              <div className="basis-1/3 flex-1">
                <Image
                  src={web4}
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                />
              </div>
              <div className="basis-1/3 flex-1">
                <Image
                  src={web5}
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                />
              </div>
              <div className="basis-1/3 flex-1">
                <Image
                  src={web6}
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                />
              </div>
            </div>
          </section>
        </div>
      </main>
    </div>
  );
}
function onClickNotAvailable() {
  throw new Error("Function not implemented.");
}
